server:
  port: 8888
#数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: wycmzxx888888..
    url: jdbc:mysql://106.53.103.231:3306/springboot_vue_demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
mybatis-plus:
  type-aliases-package: com.strQeem.pojo